# main text of home
domain_name: "leishi.io"
domain_description: "This domain is for sale!"

email: me@leishi.io

# If you want to put some external links
external_links:
    - url: "https://www.caosen.com/"
      name: "CAOSEN"
    - url: "https://www.leishi.io/"
      name: "Lei Shi"

# if it's an external image, update below for true
# better with square images
external-image: false
picture: assets/images/profile.png

# your url: http://USERNAME.github.io
url: https://www.leishi.io

# To enable google analytics, supply your token below
analytics-google: 'UA-119177383-5'

# To enable piwik tracking, supply your url & site ID below
# analytics-piwik-url: 'piwik.my-host.com'
# analytics-piwik-id: 1

# do you want a larger site? change the option below
# options: [normal, large] | default: normal
# normal = 560px / large = 810px
width: normal

# do you want some animations?
animation: true

plugins:
  - jekyll-seo-tag
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-admin

jekyll-mentions:
    base_url: https://github.com

compress_html:
    ignore:
        envs:
        - development
        - stage

exclude: ["travis.sh", "Rakefile", "README.md", "Gemfile", "Gemfile.lock", "FAQ.md", "vendor"]
